/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ConsultasDeportista;
import Controlador.ConsultasEntrenador;
import Controlador.GenerarPDF;
import Modelo.Deportistas;
import Modelo.Personas;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class InformeDeportista extends javax.swing.JInternalFrame {

    /**
     * Creates new form InformeDeportista
     */
    public InformeDeportista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblDeporte = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        lblNombresEntrenador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();

        setClosable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(234, 241, 255));

        lblNombres.setBackground(new java.awt.Color(255, 204, 204));
        lblNombres.setText("l");

        lblApellidos.setText("l");

        lblEdad.setText("l");

        lblGenero.setText("l");

        lblDeporte.setText("l");

        lblCategoria.setText("l");

        btnBuscar.setBackground(new java.awt.Color(67, 133, 243));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNombresEntrenador.setText("l");

        jLabel1.setBackground(new java.awt.Color(234, 241, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\TituloInforme.png")); // NOI18N

        btnPDF.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\btnPDF.png")); // NOI18N
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombresEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(btnPDF)
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(btnBuscar)
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnPDF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombresEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String cedula = txtCedula.getText();
    if (!cedula.isEmpty()) {
        ConsultasDeportista consulta = new ConsultasDeportista();
        Deportistas deportista = consulta.consultarDatosDeportista(cedula);
        if (deportista != null) {
            lblNombres.setText("Nombres: "+deportista.getNombres());
            lblApellidos.setText("Apellidos: "+deportista.getApellidos());
            lblEdad.setText("Edad: "+String.valueOf(deportista.getEdad()));
            lblGenero.setText("Genero: "+deportista.getGenero());
            lblDeporte.setText("Deporte: "+deportista.getDeporte()); // Aquí actualizamos el valor de lblDeporte
            lblCategoria.setText("Categoria: "+deportista.getCategoria());
            
            // Ahora podemos obtener el nombre del entrenador
            String nombresEntrenador = obtenerNombreEntrenador(deportista.getDeporte());
            if (nombresEntrenador != null) {
                lblNombresEntrenador.setText("Entrenador: "+nombresEntrenador);
            } else {
                lblNombresEntrenador.setText("No se encontró ningún entrenador para el deporte especificado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "La persona no es un deportista.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor ingresa una cédula.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        String cedula = txtCedula.getText();
    if (!cedula.isEmpty()) {
        ConsultasDeportista consulta = new ConsultasDeportista();
        Deportistas deportista = consulta.consultarDatosDeportista(cedula);
        if (deportista != null) {
            lblNombres.setText("Nombres: " + deportista.getNombres());
            lblApellidos.setText("Apellidos: " + deportista.getApellidos());
            lblEdad.setText("Edad: " + String.valueOf(deportista.getEdad()));
            lblGenero.setText("Género: " + deportista.getGenero());
            lblDeporte.setText("Deporte: " + deportista.getDeporte());
            lblCategoria.setText("Categoría: " + deportista.getCategoria());
            
            // Obtener el nombre del entrenador
            String nombresEntrenador = obtenerNombreEntrenador(deportista.getDeporte());
            
            // Generar el PDF
            GenerarPDF generadorPDF = new GenerarPDF();
            generadorPDF.generarPDF(deportista.getNombres(), deportista.getApellidos(), deportista.getEdad(), 
                                     deportista.getGenero(), deportista.getDeporte(), deportista.getCategoria(), 
                                     nombresEntrenador);
        } else {
            JOptionPane.showMessageDialog(null, "La persona no es un deportista.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor ingresa una cédula.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPDFActionPerformed

    private String obtenerNombreEntrenador(String deporte) {
    String nombresEntrenador = "";
    if (!deporte.isEmpty()) {
        ConsultasEntrenador consulta = new ConsultasEntrenador();
        Personas entrenador = consulta.buscarEntrenadorPorDeporte(deporte);
        if (entrenador != null) {
            nombresEntrenador = entrenador.getNombres() + " " + entrenador.getApellidos();
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún entrenador para el deporte especificado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor ingresa un deporte.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    return nombresEntrenador;
}

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombresEntrenador;
    public javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
