/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ConsultasDeportista;
import Controlador.ConsultasDisciplinas;
import Modelo.Deportistas;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author USUARIO
 */
public class InformeEntrenador extends javax.swing.JInternalFrame {

    /**
     * Creates new form InformeEntrenador
     */
    public InformeEntrenador() {
        initComponents();
        cargarDisciplinas();
        cargarEstadisticaGeneral();
        listDeportes.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String deporteSeleccionado = listDeportes.getSelectedItem().toString();
            if (deporteSeleccionado.equals("Elegir una opción")) {
                cargarEstadisticaGeneral();
                btnBuscar.setEnabled(false);
            } else {
                btnBuscar.setEnabled(true);
            }
        }
    });

    btnBuscar.setEnabled(false);
        
        
    }
    
    private void cargarEstadisticaGeneral() {
    // Obtener las estadísticas de deportistas
    ConsultasDeportista consulta = new ConsultasDeportista();
    Deportistas deportista = consulta.consultarEstadisticasDeportistas();

    // Establecer los valores en los JLabel
    lblPromEdad.setText("Promedio de Edad de Deportistas: " + deportista.getPromedioEdad());
    lblMasculinos.setText("Número de Deportistas Masculinos: " + deportista.getNumHombresDeportistas());
    lblFemeninos.setText("Número de Deportistas Femeninos: " + deportista.getNumMujeresDeportistas());
    lblDeporteMas.setText("Deporte con más Deportistas: " + deportista.getDeporteMasRegistros());
    lblDeporteMenos.setText("Deporte con menos Deportistas: " + deportista.getDeporteMenosRegistros());

    // Diagrama de pastel para número de deportistas por género
    DefaultPieDataset datasetGenero = new DefaultPieDataset();
    datasetGenero.setValue("Masculino", deportista.getNumHombresDeportistas());
    datasetGenero.setValue("Femenino", deportista.getNumMujeresDeportistas());
    JFreeChart chartGenero = ChartFactory.createPieChart("Distribución por Género", datasetGenero);
    ChartPanel chartPanelGenero = new ChartPanel(chartGenero);
    chartPanelGenero.setPreferredSize(new java.awt.Dimension(200, 150)); // Establecer el tamaño del gráfico
    pblGenero.removeAll();
    pblGenero.add(chartPanelGenero);
    pblGenero.revalidate();
    pblGenero.repaint();

    // Diagrama de pastel para deporte con más y menos registros
    DefaultPieDataset datasetDeporte = new DefaultPieDataset();
    datasetDeporte.setValue("Más Registros", 1); // Puedes establecer el valor según tu lógica
    datasetDeporte.setValue("Menos Registros", 1); // Puedes establecer el valor según tu lógica
    JFreeChart chartDeporte = ChartFactory.createPieChart("Deporte con más y menos Registros", datasetDeporte);
    ChartPanel chartPanelDeporte = new ChartPanel(chartDeporte);
    chartPanelDeporte.setPreferredSize(new java.awt.Dimension(200, 150)); // Establecer el tamaño del gráfico
    pnlMasoMenos.removeAll();
    pnlMasoMenos.add(chartPanelDeporte);
    pnlMasoMenos.revalidate();
    pnlMasoMenos.repaint();
}


    
    private void cargarDisciplinas() {
        ConsultasDisciplinas consultasDisciplinas = new ConsultasDisciplinas();
        List<String> disciplinas = consultasDisciplinas.consultarDisciplinas();
        
        listDeportes.removeAllItems();
        
        listDeportes.addItem("Elegir una opción");
        
        for (String disciplina : disciplinas) {
            listDeportes.addItem(disciplina);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDeporteMas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDeporteMenos = new javax.swing.JLabel();
        lblPromEdad = new javax.swing.JLabel();
        lblMasculinos = new javax.swing.JLabel();
        lblFemeninos = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        listDeportes = new javax.swing.JComboBox<>();
        btnGraficar = new javax.swing.JButton();
        pblGenero = new javax.swing.JPanel();
        pnlMasoMenos = new javax.swing.JPanel();

        setClosable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(234, 241, 255));
        jPanel1.setToolTipText("");

        lblDeporteMas.setBackground(new java.awt.Color(255, 204, 204));
        lblDeporteMas.setText("l");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\TituloInforme.png")); // NOI18N

        lblDeporteMenos.setText("l");

        lblPromEdad.setText("l");

        lblMasculinos.setText("l");

        lblFemeninos.setText("l");

        btnBuscar.setBackground(new java.awt.Color(67, 133, 243));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        listDeportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGraficar.setBackground(new java.awt.Color(52, 168, 83));
        btnGraficar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pblGeneroLayout = new javax.swing.GroupLayout(pblGenero);
        pblGenero.setLayout(pblGeneroLayout);
        pblGeneroLayout.setHorizontalGroup(
            pblGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        pblGeneroLayout.setVerticalGroup(
            pblGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMasoMenosLayout = new javax.swing.GroupLayout(pnlMasoMenos);
        pnlMasoMenos.setLayout(pnlMasoMenosLayout);
        pnlMasoMenosLayout.setHorizontalGroup(
            pnlMasoMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        pnlMasoMenosLayout.setVerticalGroup(
            pnlMasoMenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlMasoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(listDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(lblMasculinos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                                    .addComponent(lblFemeninos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblDeporteMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(34, 34, 34))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblPromEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnGraficar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pblGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(lblDeporteMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(92, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(listDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblPromEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMasculinos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFemeninos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeporteMas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficar))
                .addGap(18, 18, 18)
                .addComponent(lblDeporteMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMasoMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String deporteSeleccionado = listDeportes.getSelectedItem().toString();
        ConsultasDeportista consultasDeportista = new ConsultasDeportista();
        Deportistas estadisticasPorDeporte = consultasDeportista.consultarEstadisticasPorDeporte(deporteSeleccionado);

        lblPromEdad.setText(String.valueOf("Promedio de Edad de Deportistas: "+estadisticasPorDeporte.getPromedioEdad()));
        lblFemeninos.setText(String.valueOf("Número de Deportistas Femeninos: " +estadisticasPorDeporte.getNumMujeresDeportistas()));
        lblMasculinos.setText(String.valueOf("Número de Deportistas Masculinos: " +estadisticasPorDeporte.getNumHombresDeportistas()));
        lblDeporteMas.setText("Categoria con más Deportistas: " +estadisticasPorDeporte.getDeporteMasRegistros());
        lblDeporteMenos.setText("Categoria con menos Deportistas: " +estadisticasPorDeporte.getDeporteMenosRegistros());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        ConsultasDeportista consultasDeportista = new ConsultasDeportista();
        Deportistas estadisticas = consultasDeportista.consultarEstadisticasDeportistas();

        // Crear dataset para el primer gráfico de pastel (hombres vs mujeres)
        DefaultPieDataset dataset1 = new DefaultPieDataset();
        dataset1.setValue("Hombres", estadisticas.getNumHombresDeportistas());
        dataset1.setValue("Mujeres", estadisticas.getNumMujeresDeportistas());

        // Crear el gráfico de pastel para hombres vs mujeres
        JFreeChart chart1 = ChartFactory.createPieChart(
                "Hombres vs Mujeres",
                dataset1,
                true,
                true,
                false
        );

        // Crear dataset para el segundo gráfico de pastel (deporte más vs menos representado)
        DefaultPieDataset dataset2 = new DefaultPieDataset();
        dataset2.setValue("Más Representado", 1); // Supongamos que ya tienes el deporte más representado
        dataset2.setValue("Menos Representado", 1); // Supongamos que ya tienes el deporte menos representado

        // Crear el gráfico de pastel para deporte más vs menos representado
        JFreeChart chart2 = ChartFactory.createPieChart(
                "Categoria Más Representado vs Menos Representado",
                dataset2,
                true,
                true,
                false
        );

        // Crear el ChartPanel para el primer gráfico y establecer su tamaño
ChartPanel chartPanel1 = new ChartPanel(chart1);
chartPanel1.setPreferredSize(new java.awt.Dimension(200, 150));

// Crear el ChartPanel para el segundo gráfico y establecer su tamaño
ChartPanel chartPanel2 = new ChartPanel(chart2);
chartPanel2.setPreferredSize(new java.awt.Dimension(200, 150));

// Limpiar los paneles antes de agregar los nuevos gráficos
pblGenero.removeAll();
pnlMasoMenos.removeAll();

// Agregar los gráficos a los paneles correspondientes en la interfaz de usuario
pblGenero.setLayout(new BorderLayout());
pblGenero.add(chartPanel1, BorderLayout.CENTER);

pnlMasoMenos.setLayout(new BorderLayout());
pnlMasoMenos.add(chartPanel2, BorderLayout.CENTER);

// Refrescar la interfaz de usuario para que los cambios sean visibles
pblGenero.revalidate();
pnlMasoMenos.revalidate();
pblGenero.repaint();
pnlMasoMenos.repaint();

    }//GEN-LAST:event_btnGraficarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnGraficar;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeporteMas;
    private javax.swing.JLabel lblDeporteMenos;
    private javax.swing.JLabel lblFemeninos;
    private javax.swing.JLabel lblMasculinos;
    private javax.swing.JLabel lblPromEdad;
    private javax.swing.JComboBox<String> listDeportes;
    private javax.swing.JPanel pblGenero;
    private javax.swing.JPanel pnlMasoMenos;
    // End of variables declaration//GEN-END:variables
}
