/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import static Vista.Inicio.escritorio;
import java.awt.Dimension;



public class MenuDeportista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu
     */
    public MenuDeportista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioMenu = new javax.swing.JDesktopPane();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnBuscadorCedula = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        escritorioMenu.setBackground(new java.awt.Color(255, 255, 255));
        escritorioMenu.setPreferredSize(new java.awt.Dimension(950, 540));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\3.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\2.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\5.png")); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\4.png")); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscadorCedula.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnBuscadorCedula.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscadorCedula.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\Practicas-LigaDeportivaOtavalo\\LDCO\\src\\main\\resource\\Imagenes\\1.png")); // NOI18N
        btnBuscadorCedula.setText("Reporte ");
        btnBuscadorCedula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscadorCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscadorCedulaActionPerformed(evt);
            }
        });

        escritorioMenu.setLayer(btnRegistrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioMenu.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioMenu.setLayer(btnModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioMenu.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioMenu.setLayer(btnBuscadorCedula, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioMenuLayout = new javax.swing.GroupLayout(escritorioMenu);
        escritorioMenu.setLayout(escritorioMenuLayout);
        escritorioMenuLayout.setHorizontalGroup(
            escritorioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escritorioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscadorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(806, Short.MAX_VALUE))
        );
        escritorioMenuLayout.setVerticalGroup(
            escritorioMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscadorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       RegistrarDeportista ventanaRC = new RegistrarDeportista();
escritorio.add(ventanaRC);

// Obtener el tamaño del escritorio
Dimension tamañoEscritorio = escritorio.getSize();

// Obtener el tamaño de la ventana interna
Dimension tamañoVentana = ventanaRC.getSize();

// Establecer la posición de la ventana interna en el lado derecho del escritorio
int x = tamañoEscritorio.width - tamañoVentana.width; // Posición x en el borde derecho
int y = (tamañoEscritorio.height - tamañoVentana.height) / 2; // Centrado verticalmente
ventanaRC.setLocation(x, y);

// Mostrar la ventana interna
ventanaRC.setVisible(true);
;
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        EliminarDeportista ventanaRC = new EliminarDeportista();
escritorio.add(ventanaRC);

// Obtener el tamaño del escritorio
Dimension tamañoEscritorio = escritorio.getSize();

// Obtener el tamaño de la ventana interna
Dimension tamañoVentana = ventanaRC.getSize();

// Establecer la posición de la ventana interna en el lado derecho del escritorio
int x = tamañoEscritorio.width - tamañoVentana.width; // Posición x en el borde derecho
int y = (tamañoEscritorio.height - tamañoVentana.height) / 2; // Centrado verticalmente
ventanaRC.setLocation(x, y);

// Mostrar la ventana interna
ventanaRC.setVisible(true);

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        CambioDisciplina ventanaRC = new CambioDisciplina();
        escritorio.add(ventanaRC);

// Obtener el tamaño del escritorio
Dimension tamañoEscritorio = escritorio.getSize();

// Obtener el tamaño de la ventana interna
Dimension tamañoVentana = ventanaRC.getSize();

// Establecer la posición de la ventana interna en el lado derecho del escritorio
int x = tamañoEscritorio.width - tamañoVentana.width; // Posición x en el borde derecho
int y = (tamañoEscritorio.height - tamañoVentana.height) / 2; // Centrado verticalmente
ventanaRC.setLocation(x, y);

// Mostrar la ventana interna
ventanaRC.setVisible(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BuscadorDeportistas ventanaRC = new BuscadorDeportistas();
        escritorio.add(ventanaRC);
        // Obtener el tamaño del escritorio
Dimension tamañoEscritorio = escritorio.getSize();

// Obtener el tamaño de la ventana interna
Dimension tamañoVentana = ventanaRC.getSize();

// Establecer la posición de la ventana interna en el lado derecho del escritorio
int x = tamañoEscritorio.width - tamañoVentana.width; // Posición x en el borde derecho
int y = (tamañoEscritorio.height - tamañoVentana.height) / 2; // Centrado verticalmente
ventanaRC.setLocation(x, y);

// Mostrar la ventana interna
ventanaRC.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscadorCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorCedulaActionPerformed
        InformeDeportista ventanaRC = new InformeDeportista();
        escritorio.add(ventanaRC);
        // Obtener el tamaño del escritorio
Dimension tamañoEscritorio = escritorio.getSize();

// Obtener el tamaño de la ventana interna
Dimension tamañoVentana = ventanaRC.getSize();

// Establecer la posición de la ventana interna en el lado derecho del escritorio
int x = tamañoEscritorio.width - tamañoVentana.width; // Posición x en el borde derecho
int y = (tamañoEscritorio.height - tamañoVentana.height) / 2; // Centrado verticalmente
ventanaRC.setLocation(x, y);

// Mostrar la ventana interna
ventanaRC.setVisible(true);
    }//GEN-LAST:event_btnBuscadorCedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscadorCedula;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JDesktopPane escritorioMenu;
    // End of variables declaration//GEN-END:variables
}
